version: '3.7'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'web-bentaya'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    restart: 'no'
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0
    ports:
      - '10000:10000'
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    restart: 'no'
