insert into poll(id, description, name)
values (1, 'Votación para las canciones del Disco Bentaya', 'Disco Bentaya');

insert into poll_option(id, name, description, poll_id)
values (1, 'Historia de un scout', 'T.S. Autindana, C.V. La Palma 1986', 1),
       (2, 'Vida en la tropa', '1981', 1),
       (3, 'Nuestra amiga la ardilla', 'Manadas Baobab y Waigunga, 1987', 1),
       (4, 'Busca  a BP', 'T. S. Arteteifac, 1987 ', 1),
       (5, 'BP era su nombre', 'T. S. Arteteifac, 1987', 1),
       (6, 'Todo empezó cuando te ví', 'U.E. Aridane, 1987', 1),
       (7, 'Forjamos la paz', 'C.R. Idafe, 1987', 1),
       (8, 'Canciones', 'C.R. Idafe, C.V. Gerona 1991', 1),
       (9, 'El Blues De La Manada', 'Manadas Baobab y Waigunga, C.V. Tenerife 1992', 1),
       (10, 'Un grito de Alegría', 'U. E. Aridane, C.V. Arenas Negras 1992', 1),
       (11, 'Su Bau Yau', 'Manadas Baobab y Waigunga, C.V. Plan 1993', 1),
       (12, 'Sensaciones', 'T. S. Arteteifac , C.V. Plan 1993', 1),
       (13, 'Momentos de unidad', 'T.S. Autindana, C.V. Plan 1993', 1),
       (14, 'Haciendo Escultismo', 'C.R. Idafe, C.V. Plan 1993', 1),
       (15, 'Aprovecha tu vida', 'T.S. Arteteifac, C.V. Peñascosa 1994', 1),
       (16, 'La Sonrisa De Un Amigo', 'T.S. Autindana, C.V. Peñascosa 1994', 1),
       (17, 'Escucha A Los Castores', 'C. Garajonay, C.V. Escorial 1996', 1),
       (18, 'El Baile De Baloo', 'Manadas Baobab y Waigunga, C.V. El Escorial 1996', 1),
       (19, 'En Unidad', 'U.E. Aridane, C.V. El Escorial 1996', 1),
       (20, 'Reggae de la selva', 'Manadas Baobab y Waigunga y Colonia de castores “Garajonay”, C.V. Bielsa 1998', 1),
       (21, 'Siempre hay un amigo', 'T. S. Arteteifac, C.V. Bielsa 1998', 1),
       (22, 'Las Máximas', 'C.R. Idafe, Bielsa 1998', 1),
       (23, 'Los primeros castores de la historia', 'C. Garajonay, C.V. Ávila 2003', 1),
       (24, '¿A “Londres” vas?', 'Manada Waigunga, Harlow Londres 2007', 1),
       (25, 'Sale el sol', 'Manadas Baobab y Waigunga, C.V. Asturias 2008', 1),
       (26, 'El clanso', 'C.R. Idafe, C.V. Asturias 2008', 1),
       (27, 'Soy un banderlog', 'Manadas Baobab y Waigunga, Sao Jacinto 2009', 1),
       (28, 'Vuelvo a sentir', 'T.S. Arteteifac, C.V. Sao Jacinto 2009', 1),
       (29, 'Juanito “el batalla”', 'C.R. Idafe, C.V. Cuenca 2011', 1),
       (30, 'Sigue tu ritmo', 'Manadas Baobab y Waigunga, C.V. Cuenca 2011', 1),
       (31, 'Y ahora ven', 'Manada, C.V. Ávila 2012', 1),
       (32, 'Vívelo', 'C.V. Albacete 2013', 1),
       (33, 'Efecto esculta', 'U. E. Aridane, C.V. Albacete 2013', 1),
       (34, 'Caminando', 'U. E. Aridane, C.V. Ávila 2015', 1),
       (35, 'Ese eres tú', 'C. R. Idafe, C.V. Soria 2018', 1),
       (36, 'Efecto boomerang', 'C. R. Idafe, C.V. Valencia 2019', 1),
       (37, 'Clan Igafe', 'C. R. Idafe, C.V. Arucas 2020', 1),
       (38, 'Elección de vida', 'C.R. Idafe, C.V. Teruel 2023', 1),
       (39, 'Como ha pasado el tiempo', 'Grupo Scout 105 Bentaya', 1),
       (40, 'Recuerdos', 'Grupo Scout 105 Bentaya', 1),
       (41, 'Siento que sí', 'Grupo Scout 105 Bentaya', 1),
       (43, 'Nado arriba', 'Grupo Scout 105 Bentaya', 1),
       (45, 'Te vas de la manada', 'Grupo Scout 105 Bentaya', 1),
       (46, 'Imidagüen desde hoy', 'Grupo Scout 105 Bentaya', 1),
       (47, 'Despedida esculta', 'Grupo Scout 105 Bentaya', 1),
       (48, 'La laguna azul', 'Grupo Scout 105 Bentaya', 1);


insert into poll_attachment(id, link, poll_option_id)
values (1, 'https://www.youtube.com/watch?v=FT40PpsFSHA', 29),
       (2, 'https://www.youtube.com/watch?v=NZ2SKscg5Ew', 30),
       (3, 'https://www.youtube.com/watch?v=69DfdVjVS6M', 30),
       (4, 'https://www.youtube.com/watch?v=VWiuVsDHL2k', 31),
       (5, 'https://www.youtube.com/watch?v=GEVEl-npGUU', 33),
       (6, 'https://www.youtube.com/watch?v=GZ9HtY2j6A0', 34);

