# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - web-bentaya-test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Install Redsys lib
        run: mvn install:install-file -Dfile=\${project.basedir}/libs/apiSha256.jar -DgroupId=sis.redsys.api -DartifactId=api-sha256 -Dversion=2.3 -Dpackaging=jar

      - name: Build with Maven
        run: mvn clean package -DskipTests -Pprod

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AF3EBF27A8C642C78D41939F779A9B7D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_874696B8AE074658A19921DDAFF58359 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_393DBCD3A2DB432696FFBA27A773BAE8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'web-bentaya-test'
          slot-name: 'Production'
          package: '${{ github.workspace }}/target/*.jar'